package com.neplus.erp.mapper;

import com.neplus.erp.model.TmClientPO;
import com.neplus.erp.model.TmClientPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TmClientPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_client
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    long countByExample(TmClientPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_client
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    int deleteByExample(TmClientPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_client
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    int deleteByPrimaryKey(Integer clientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_client
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    int insert(TmClientPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_client
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    int insertSelective(TmClientPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_client
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    List<TmClientPO> selectByExample(TmClientPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_client
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    TmClientPO selectByPrimaryKey(Integer clientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_client
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    int updateByExampleSelective(@Param("record") TmClientPO record, @Param("example") TmClientPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_client
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    int updateByExample(@Param("record") TmClientPO record, @Param("example") TmClientPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_client
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    int updateByPrimaryKeySelective(TmClientPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_client
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    int updateByPrimaryKey(TmClientPO record);
}