package com.neplus.erp.mapper;

import com.neplus.erp.model.TmDeptPO;
import com.neplus.erp.model.TmDeptPOExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TmDeptPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_dept
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    long countByExample(TmDeptPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_dept
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    int deleteByExample(TmDeptPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_dept
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    int deleteByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_dept
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    int insert(TmDeptPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_dept
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    int insertSelective(TmDeptPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_dept
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    List<TmDeptPO> selectByExample(TmDeptPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_dept
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    TmDeptPO selectByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_dept
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    int updateByExampleSelective(@Param("record") TmDeptPO record, @Param("example") TmDeptPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_dept
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    int updateByExample(@Param("record") TmDeptPO record, @Param("example") TmDeptPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_dept
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    int updateByPrimaryKeySelective(TmDeptPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_dept
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    int updateByPrimaryKey(TmDeptPO record);
}