package com.neplus.erp.mapper;

import com.neplus.erp.model.TmPostPO;
import com.neplus.erp.model.TmPostPOExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TmPostPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_post
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    long countByExample(TmPostPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_post
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    int deleteByExample(TmPostPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_post
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    int deleteByPrimaryKey(Integer postId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_post
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    int insert(TmPostPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_post
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    int insertSelective(TmPostPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_post
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    List<TmPostPO> selectByExample(TmPostPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_post
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    TmPostPO selectByPrimaryKey(Integer postId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_post
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    int updateByExampleSelective(@Param("record") TmPostPO record, @Param("example") TmPostPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_post
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    int updateByExample(@Param("record") TmPostPO record, @Param("example") TmPostPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_post
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    int updateByPrimaryKeySelective(TmPostPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_post
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    int updateByPrimaryKey(TmPostPO record);
}