package com.neplus.erp.mapper;

import com.neplus.erp.model.TmUserPO;
import com.neplus.erp.model.TmUserPOExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TmUserPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Tue Jul 30 16:01:49 CEST 2024
     */
    long countByExample(TmUserPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Tue Jul 30 16:01:49 CEST 2024
     */
    int deleteByExample(TmUserPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Tue Jul 30 16:01:49 CEST 2024
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Tue Jul 30 16:01:49 CEST 2024
     */
    int insert(TmUserPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Tue Jul 30 16:01:49 CEST 2024
     */
    int insertSelective(TmUserPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Tue Jul 30 16:01:49 CEST 2024
     */
    List<TmUserPO> selectByExample(TmUserPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Tue Jul 30 16:01:49 CEST 2024
     */
    TmUserPO selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Tue Jul 30 16:01:49 CEST 2024
     */
    int updateByExampleSelective(@Param("record") TmUserPO record, @Param("example") TmUserPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Tue Jul 30 16:01:49 CEST 2024
     */
    int updateByExample(@Param("record") TmUserPO record, @Param("example") TmUserPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Tue Jul 30 16:01:49 CEST 2024
     */
    int updateByPrimaryKeySelective(TmUserPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Tue Jul 30 16:01:49 CEST 2024
     */
    int updateByPrimaryKey(TmUserPO record);
}