package com.neplus.erp.mapper;

import com.neplus.erp.model.TrUserRolePO;
import com.neplus.erp.model.TrUserRolePOExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TrUserRolePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    long countByExample(TrUserRolePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    int deleteByExample(TrUserRolePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    int insert(TrUserRolePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    int insertSelective(TrUserRolePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    List<TrUserRolePO> selectByExample(TrUserRolePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    TrUserRolePO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    int updateByExampleSelective(@Param("record") TrUserRolePO record, @Param("example") TrUserRolePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    int updateByExample(@Param("record") TrUserRolePO record, @Param("example") TrUserRolePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    int updateByPrimaryKeySelective(TrUserRolePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    int updateByPrimaryKey(TrUserRolePO record);
}