package com.neplus.erp.mapper;

import com.neplus.erp.model.TrUserPostPO;
import com.neplus.erp.model.TrUserPostPOExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TrUserPostPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_post
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    long countByExample(TrUserPostPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_post
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    int deleteByExample(TrUserPostPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_post
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_post
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    int insert(TrUserPostPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_post
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    int insertSelective(TrUserPostPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_post
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    List<TrUserPostPO> selectByExample(TrUserPostPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_post
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    TrUserPostPO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_post
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    int updateByExampleSelective(@Param("record") TrUserPostPO record, @Param("example") TrUserPostPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_post
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    int updateByExample(@Param("record") TrUserPostPO record, @Param("example") TrUserPostPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_post
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    int updateByPrimaryKeySelective(TrUserPostPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_post
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    int updateByPrimaryKey(TrUserPostPO record);
}