package com.neplus.erp.mapper;

import com.neplus.erp.model.TtMailLogPO;
import com.neplus.erp.model.TtMailLogPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TtMailLogPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_mail_log
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    long countByExample(TtMailLogPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_mail_log
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    int deleteByExample(TtMailLogPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_mail_log
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    int deleteByPrimaryKey(Integer mailLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_mail_log
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    int insert(TtMailLogPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_mail_log
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    int insertSelective(TtMailLogPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_mail_log
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    List<TtMailLogPO> selectByExampleWithBLOBs(TtMailLogPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_mail_log
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    List<TtMailLogPO> selectByExample(TtMailLogPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_mail_log
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    TtMailLogPO selectByPrimaryKey(Integer mailLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_mail_log
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    int updateByExampleSelective(@Param("record") TtMailLogPO record, @Param("example") TtMailLogPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_mail_log
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    int updateByExampleWithBLOBs(@Param("record") TtMailLogPO record, @Param("example") TtMailLogPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_mail_log
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    int updateByExample(@Param("record") TtMailLogPO record, @Param("example") TtMailLogPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_mail_log
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    int updateByPrimaryKeySelective(TtMailLogPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_mail_log
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    int updateByPrimaryKeyWithBLOBs(TtMailLogPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_mail_log
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    int updateByPrimaryKey(TtMailLogPO record);
}