package com.neplus.erp.mapper;

import com.neplus.erp.model.TtMailTemplatePO;
import com.neplus.erp.model.TtMailTemplatePOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TtMailTemplatePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_mail_template
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    long countByExample(TtMailTemplatePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_mail_template
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    int deleteByExample(TtMailTemplatePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_mail_template
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    int deleteByPrimaryKey(Integer templateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_mail_template
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    int insert(TtMailTemplatePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_mail_template
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    int insertSelective(TtMailTemplatePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_mail_template
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    List<TtMailTemplatePO> selectByExampleWithBLOBs(TtMailTemplatePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_mail_template
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    List<TtMailTemplatePO> selectByExample(TtMailTemplatePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_mail_template
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    TtMailTemplatePO selectByPrimaryKey(Integer templateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_mail_template
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    int updateByExampleSelective(@Param("record") TtMailTemplatePO record, @Param("example") TtMailTemplatePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_mail_template
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    int updateByExampleWithBLOBs(@Param("record") TtMailTemplatePO record, @Param("example") TtMailTemplatePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_mail_template
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    int updateByExample(@Param("record") TtMailTemplatePO record, @Param("example") TtMailTemplatePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_mail_template
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    int updateByPrimaryKeySelective(TtMailTemplatePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_mail_template
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    int updateByPrimaryKeyWithBLOBs(TtMailTemplatePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_mail_template
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    int updateByPrimaryKey(TtMailTemplatePO record);
}