package com.neplus.erp.mapper;

import com.neplus.erp.model.TtTaskPO;
import com.neplus.erp.model.TtTaskPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TtTaskPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_task
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    long countByExample(TtTaskPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_task
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    int deleteByExample(TtTaskPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_task
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    int deleteByPrimaryKey(Integer taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_task
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    int insert(TtTaskPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_task
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    int insertSelective(TtTaskPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_task
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    List<TtTaskPO> selectByExample(TtTaskPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_task
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    TtTaskPO selectByPrimaryKey(Integer taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_task
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    int updateByExampleSelective(@Param("record") TtTaskPO record, @Param("example") TtTaskPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_task
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    int updateByExample(@Param("record") TtTaskPO record, @Param("example") TtTaskPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_task
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    int updateByPrimaryKeySelective(TtTaskPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_task
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    int updateByPrimaryKey(TtTaskPO record);
}