package com.neplus.erp.mapper;

import com.neplus.erp.model.TtTaskProcessPO;
import com.neplus.erp.model.TtTaskProcessPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TtTaskProcessPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_task_process
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    long countByExample(TtTaskProcessPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_task_process
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    int deleteByExample(TtTaskProcessPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_task_process
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    int deleteByPrimaryKey(Integer processId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_task_process
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    int insert(TtTaskProcessPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_task_process
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    int insertSelective(TtTaskProcessPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_task_process
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    List<TtTaskProcessPO> selectByExample(TtTaskProcessPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_task_process
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    TtTaskProcessPO selectByPrimaryKey(Integer processId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_task_process
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    int updateByExampleSelective(@Param("record") TtTaskProcessPO record, @Param("example") TtTaskProcessPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_task_process
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    int updateByExample(@Param("record") TtTaskProcessPO record, @Param("example") TtTaskProcessPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_task_process
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    int updateByPrimaryKeySelective(TtTaskProcessPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_task_process
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    int updateByPrimaryKey(TtTaskProcessPO record);
}