package com.neplus.erp.model;

import java.io.Serializable;
import java.util.Date;

public class TmRolePO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_role.role_id
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_role.role_code
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    private String roleCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_role.role_name
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_role.role_type
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    private Integer roleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_role.role_status
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    private Integer roleStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_role.is_delete
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    private Integer isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_role.create_by
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_role.create_date
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_role.update_by
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_role.update_date
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tm_role
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_role.role_id
     *
     * @return the value of tm_role.role_id
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_role.role_id
     *
     * @param roleId the value for tm_role.role_id
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_role.role_code
     *
     * @return the value of tm_role.role_code
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_role.role_code
     *
     * @param roleCode the value for tm_role.role_code
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_role.role_name
     *
     * @return the value of tm_role.role_name
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_role.role_name
     *
     * @param roleName the value for tm_role.role_name
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_role.role_type
     *
     * @return the value of tm_role.role_type
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public Integer getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_role.role_type
     *
     * @param roleType the value for tm_role.role_type
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public void setRoleType(Integer roleType) {
        this.roleType = roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_role.role_status
     *
     * @return the value of tm_role.role_status
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public Integer getRoleStatus() {
        return roleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_role.role_status
     *
     * @param roleStatus the value for tm_role.role_status
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public void setRoleStatus(Integer roleStatus) {
        this.roleStatus = roleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_role.is_delete
     *
     * @return the value of tm_role.is_delete
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_role.is_delete
     *
     * @param isDelete the value for tm_role.is_delete
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_role.create_by
     *
     * @return the value of tm_role.create_by
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_role.create_by
     *
     * @param createBy the value for tm_role.create_by
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_role.create_date
     *
     * @return the value of tm_role.create_date
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_role.create_date
     *
     * @param createDate the value for tm_role.create_date
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_role.update_by
     *
     * @return the value of tm_role.update_by
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_role.update_by
     *
     * @param updateBy the value for tm_role.update_by
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_role.update_date
     *
     * @return the value of tm_role.update_date
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_role.update_date
     *
     * @param updateDate the value for tm_role.update_date
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}