package com.neplus.erp.model;

import java.io.Serializable;
import java.util.Date;

public class TmUserPO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_user.user_id
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_user.user_code
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    private String userCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_user.user_name
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_user.password
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_user.sex
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_user.phone
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_user.mobile
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_user.email
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_user.birthday
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_user.avatar
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_user.email_token
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    private String emailToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_user.user_type
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    private Integer userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_user.user_status
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    private Integer userStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_user.is_delete
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    private Integer isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_user.create_date
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_user.create_by
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_user.update_date
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_user.update_by
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tm_user
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_user.user_id
     *
     * @return the value of tm_user.user_id
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_user.user_id
     *
     * @param userId the value for tm_user.user_id
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_user.user_code
     *
     * @return the value of tm_user.user_code
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_user.user_code
     *
     * @param userCode the value for tm_user.user_code
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_user.user_name
     *
     * @return the value of tm_user.user_name
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_user.user_name
     *
     * @param userName the value for tm_user.user_name
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_user.password
     *
     * @return the value of tm_user.password
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_user.password
     *
     * @param password the value for tm_user.password
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_user.sex
     *
     * @return the value of tm_user.sex
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_user.sex
     *
     * @param sex the value for tm_user.sex
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_user.phone
     *
     * @return the value of tm_user.phone
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_user.phone
     *
     * @param phone the value for tm_user.phone
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_user.mobile
     *
     * @return the value of tm_user.mobile
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_user.mobile
     *
     * @param mobile the value for tm_user.mobile
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_user.email
     *
     * @return the value of tm_user.email
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_user.email
     *
     * @param email the value for tm_user.email
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_user.birthday
     *
     * @return the value of tm_user.birthday
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_user.birthday
     *
     * @param birthday the value for tm_user.birthday
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_user.avatar
     *
     * @return the value of tm_user.avatar
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_user.avatar
     *
     * @param avatar the value for tm_user.avatar
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_user.email_token
     *
     * @return the value of tm_user.email_token
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    public String getEmailToken() {
        return emailToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_user.email_token
     *
     * @param emailToken the value for tm_user.email_token
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    public void setEmailToken(String emailToken) {
        this.emailToken = emailToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_user.user_type
     *
     * @return the value of tm_user.user_type
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_user.user_type
     *
     * @param userType the value for tm_user.user_type
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_user.user_status
     *
     * @return the value of tm_user.user_status
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    public Integer getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_user.user_status
     *
     * @param userStatus the value for tm_user.user_status
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    public void setUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_user.is_delete
     *
     * @return the value of tm_user.is_delete
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_user.is_delete
     *
     * @param isDelete the value for tm_user.is_delete
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_user.create_date
     *
     * @return the value of tm_user.create_date
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_user.create_date
     *
     * @param createDate the value for tm_user.create_date
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_user.create_by
     *
     * @return the value of tm_user.create_by
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_user.create_by
     *
     * @param createBy the value for tm_user.create_by
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_user.update_date
     *
     * @return the value of tm_user.update_date
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_user.update_date
     *
     * @param updateDate the value for tm_user.update_date
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_user.update_by
     *
     * @return the value of tm_user.update_by
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_user.update_by
     *
     * @param updateBy the value for tm_user.update_by
     *
     * @mbg.generated Sun Jan 12 19:03:26 CET 2025
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }
}