package com.neplus.erp.model;

import java.io.Serializable;
import java.util.Date;

public class TtTaskPO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_task.task_id
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private Integer taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_task.client_id
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private Integer clientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_task.task_name
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private String taskName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_task.task_type
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private Integer taskType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_task.task_status
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private Integer taskStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_task.dec_draft_file
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private Integer decDraftFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_task.dec_draft_send_date
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private Date decDraftSendDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_task.dec_form_file
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private Integer decFormFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_task.dec_form_send_date
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private Date decFormSendDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_task.is_fetch_doc
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private Integer isFetchDoc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_task.is_delete
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private Integer isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_task.create_by
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_task.create_date
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_task.update_by
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_task.update_date
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tt_task
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_task.task_id
     *
     * @return the value of tt_task.task_id
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_task.task_id
     *
     * @param taskId the value for tt_task.task_id
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_task.client_id
     *
     * @return the value of tt_task.client_id
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public Integer getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_task.client_id
     *
     * @param clientId the value for tt_task.client_id
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_task.task_name
     *
     * @return the value of tt_task.task_name
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_task.task_name
     *
     * @param taskName the value for tt_task.task_name
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_task.task_type
     *
     * @return the value of tt_task.task_type
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public Integer getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_task.task_type
     *
     * @param taskType the value for tt_task.task_type
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public void setTaskType(Integer taskType) {
        this.taskType = taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_task.task_status
     *
     * @return the value of tt_task.task_status
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public Integer getTaskStatus() {
        return taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_task.task_status
     *
     * @param taskStatus the value for tt_task.task_status
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public void setTaskStatus(Integer taskStatus) {
        this.taskStatus = taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_task.dec_draft_file
     *
     * @return the value of tt_task.dec_draft_file
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public Integer getDecDraftFile() {
        return decDraftFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_task.dec_draft_file
     *
     * @param decDraftFile the value for tt_task.dec_draft_file
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public void setDecDraftFile(Integer decDraftFile) {
        this.decDraftFile = decDraftFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_task.dec_draft_send_date
     *
     * @return the value of tt_task.dec_draft_send_date
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public Date getDecDraftSendDate() {
        return decDraftSendDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_task.dec_draft_send_date
     *
     * @param decDraftSendDate the value for tt_task.dec_draft_send_date
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public void setDecDraftSendDate(Date decDraftSendDate) {
        this.decDraftSendDate = decDraftSendDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_task.dec_form_file
     *
     * @return the value of tt_task.dec_form_file
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public Integer getDecFormFile() {
        return decFormFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_task.dec_form_file
     *
     * @param decFormFile the value for tt_task.dec_form_file
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public void setDecFormFile(Integer decFormFile) {
        this.decFormFile = decFormFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_task.dec_form_send_date
     *
     * @return the value of tt_task.dec_form_send_date
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public Date getDecFormSendDate() {
        return decFormSendDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_task.dec_form_send_date
     *
     * @param decFormSendDate the value for tt_task.dec_form_send_date
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public void setDecFormSendDate(Date decFormSendDate) {
        this.decFormSendDate = decFormSendDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_task.is_fetch_doc
     *
     * @return the value of tt_task.is_fetch_doc
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public Integer getIsFetchDoc() {
        return isFetchDoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_task.is_fetch_doc
     *
     * @param isFetchDoc the value for tt_task.is_fetch_doc
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public void setIsFetchDoc(Integer isFetchDoc) {
        this.isFetchDoc = isFetchDoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_task.is_delete
     *
     * @return the value of tt_task.is_delete
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_task.is_delete
     *
     * @param isDelete the value for tt_task.is_delete
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_task.create_by
     *
     * @return the value of tt_task.create_by
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_task.create_by
     *
     * @param createBy the value for tt_task.create_by
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_task.create_date
     *
     * @return the value of tt_task.create_date
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_task.create_date
     *
     * @param createDate the value for tt_task.create_date
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_task.update_by
     *
     * @return the value of tt_task.update_by
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_task.update_by
     *
     * @param updateBy the value for tt_task.update_by
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_task.update_date
     *
     * @return the value of tt_task.update_date
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_task.update_date
     *
     * @param updateDate the value for tt_task.update_date
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}